% separate_by_tag.m  —  auto-generated by waveform_analyzer.m
% Run this to re-sort DEFECTIVE files into sub-folders by tag keyword.
% Edit TAG_MAP to add or rename categories.
clc; clear;
defective_folder = 'D:\\THI IAE 3rd_semester_summer_2026\\Hiwi EIS\\Code\\Signal Pre Processing\\data\\Defective';

TAG_MAP = {
    'AMBIGUOUS_FREQ',    'Tag_AmbiguousFreq';
    'FREQ_MISMATCH',     'Tag_FreqMismatch';
    'LOW_SNR',           'Tag_LowSNR';
    'HIGH_THD',          'Tag_HighTHD';
    'NOT_SINUSOIDAL',    'Tag_NotSinusoidal';
    'FLAT',              'Tag_FlatSignal';
    'LEADING_ZEROS',     'Tag_EdgeZeros';
    'TRAILING_ZEROS',    'Tag_EdgeZeros';
    'NAN_INF',           'Tag_NaNInf';
};

files = dir(fullfile(defective_folder, '*DEFECTIVE*.csv'));
for k = 1:length(files)
    fname   = files(k).name;
    matched = false;
    for t = 1:size(TAG_MAP,1)
        if contains(fname, TAG_MAP{t,1}, 'IgnoreCase', true)
            dest = fullfile(defective_folder, TAG_MAP{t,2});
            if ~exist(dest,'dir'), mkdir(dest); end
            copyfile(fullfile(defective_folder,fname), fullfile(dest,fname));
            fprintf('  %s  →  %s\n', fname, TAG_MAP{t,2});
            matched = true; break;
        end
    end
    if ~matched
        fprintf('  %s  →  (unmatched, stays in Defective/)\n', fname);
    end
end
disp('Separation complete.');
